FROM golang:1.19-alpine as build

WORKDIR /moss-communication-server


COPY moss-communication-server/go.mod .
COPY moss-communication-server/go.sum .
RUN go mod download

COPY ./moss-communication-server ./moss-communication-server

ENV PORT 8080
RUN go build -tags staging -o /moss-communication-server/bin/moss-communication-server moss-communication-server/cmd/main.go

# Deploy
FROM alpine:3.16

WORKDIR /moss-communication-server
COPY --from=build /moss-communication-server/bin/moss-communication-server /moss-communication-server/bin/moss-communication-server

# Create a group and user
RUN addgroup -S appgroup && adduser -S appuser -G appgroup

# Tell docker that all future commands should run as the appuser user
USER appuser

EXPOSE 8080

ENTRYPOINT ["/moss-communication-server/bin/moss-communication-server"]
